export const FETCH_ALL_PHOTOS_SUCCESS = 'FETCH_ALL_PHOTOS_SUCCESS';
export const FETCH_ALL_PHOTOS_ERROR = 'FETCH_ALL_PHOTOS_ERROR';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_ERROR = 'FETCH_SEARCH_RESULTS_ERROR';
export const TOGGLE_LIKES_SUCCESS = 'TOGGLE_LIKES_SUCCESS';
export const TOGGLE_LIKES_ERROR = 'TOGGLE_LIKES_ERROR';
