export const FETCH_ALL_PHOTOS_SUCCESS = 'FETCH_ALL_PHOTOS_SUCCESS';
export const FETCH_ALL_PHOTOS_ERROR = 'FETCH_ALL_PHOTOS_ERROR';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_ERROR = 'FETCH_SEARCH_RESULTS_ERROR';
